SRCS=GUIDialogAudioSubtitleSettings.cpp \
     GUIDialogFullScreenInfo.cpp \
     GUIDialogSubtitles.cpp \
     GUIDialogTeletext.cpp \
     GUIDialogVideoBookmarks.cpp \
     GUIDialogVideoInfo.cpp \
     GUIDialogVideoOSD.cpp \
     GUIDialogVideoSettings.cpp \

LIB=videodialogs.a

include @abs_top_builddir@/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
