SRCS=PVRRecording.cpp \
     PVRRecordings.cpp \
     PVRRecordingsPath.cpp

LIB=pvrrecordings.a

include @abs_top_builddir@/Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
